#!/bin/bash
set -x
/cygdrive/c/VulkanSDK/1.1.70.1/Bin32/glslangValidator.exe -V shader.vert

/cygdrive/c/VulkanSDK/1.1.70.1/Bin32/glslangValidator.exe -V shader.frag

/cygdrive/c/VulkanSDK/1.1.70.1/Bin32/glslangValidator.exe -V shader.geom
