(in-package :vktk)

(defclass imgui (vulkan-module)
  ((mouse-cursors :initform (make-array ig::ImGuiMouseCursor_Count :initial-element nil) :reader mouse-cursors)
   (mouse-pressed :initform (make-array 3 :initial-element nil) :reader mouse-pressed)
   (mouse-just-pressed :initform (make-array 5 :initial-element nil) :reader mouse-just-pressed)
   (mouse-wheel-vertical :initform 0.0f0 :accessor mouse-wheel-vertical)
   (mouse-wheel-horizontal :initform 0.0f0 :accessor mouse-wheel-horizontal)
   (prev-user-callback-mouse-button :initform nil :accessor prev-user-callback-mouse-button)
   (prev-user-callback-scroll :initform nil :accessor prev-user-callback-scroll)
   (prev-user-callback-key :initform nil :accessor prev-user-callback-key)
   (prev-user-callback-char :initform nil :accessor prev-user-callback-char)
   (prev-user-monitor-callback :initform nil :accessor prev-user-monitor-callback)
   (render-pass :accessor render-pass :initform nil) ;; todo: try to make independent of render-pass
   (pipeline-cache :initform +null-pipeline-cache+ :accessor pipeline-cache :initarg :pipeline-cache)
   (descriptor-pool :accessor descriptor-pool :initform nil :initarg :descriptor-pool)
   (err :initform 0 :accessor imgui-err)
   (buffer-memory-alignment :initform 64 :accessor buffer-memory-alignment)
   (pipeline-create-flags :initform 0 :accessor pipeline-create-flags)
   (descriptor-set-layout :accessor descriptor-set-layout :initform nil)
   (pipeline-layout :accessor pipeline-layout :initform nil)
   (descriptor-set :accessor descriptor-set :initform nil)
   (pipeline :accessor pipeline :initform nil)
   (font-sampler :accessor font-sampler :initform nil)
   (font-memory :accessor font-memory :initform nil)
   (font-image :accessor font-image :initform nil)
   (font-view :accessor font-view :initform nil)
   (upload-buffer-memory :accessor upload-buffer-memory :initform nil)
   (upload-buffer :accessor upload-buffer :initform nil)
   (imgui-context :accessor imgui-context :initform nil)
   (imgui-time :accessor imgui-time :initform 0.0f0)
   (frame-count :accessor frame-count)
   (frame-data :initform nil :accessor frame-data)
   (want-update-monitors? :initform t :accessor want-update-monitors?)
   (main-window :initform nil :initarg :main-window :accessor main-window)))


(defmethod vulkan-instance ((imgui imgui))
  (vulkan-instance (vk::application imgui)))

(defmethod physical-device ((imgui imgui))
  (physical-device (default-logical-device (vk::application imgui))))

(defmethod logical-device ((imgui imgui))
  (default-logical-device (vk::application imgui)))

(defmethod allocator ((imgui imgui))
  (allocator (vk::application imgui)))
