(in-package :cl-user)

(defpackage :imgui
  (:nicknames :ig)
  (:export #:ImGuiVec2
	   #:ImGuiVec4
	   
	   #:ImGuiWindowFlags_NoTitleBar
	   #:ImGuiWindowFlags_NoResize
	   #:ImGuiWindowFlags_NoMove
	   #:ImGuiWindowFlags_NoScrollbar
	   #:ImGuiWindowFlags_NoScrollWithMouse
	   #:ImGuiWindowFlags_NoCollapse
	   #:ImGuiWindowFlags_AlwaysAutoResize
	   #:ImGuiWindowFlags_NoSavedSettings
	   #:ImGuiWindowFlags_NoInputs
	   #:ImGuiWindowFlags_MenuBar
	   #:ImGuiWindowFlags_HorizontalScrollbar
	   #:ImGuiWindowFlags_NoFocusOnAppearing
	   #:ImGuiWindowFlags_NoBringToFrontOnFocus
	   #:ImGuiWindowFlags_AlwaysVerticalScrollbar
	   #:ImGuiWindowFlags_AlwaysHorizontalScrollbar
	   #:ImGuiWindowFlags_AlwaysUseWindowPadding
	   #:ImGuiWindowFlags_ResizeFromAnySide
	   
	   #:ImGuiInputTextFlags_CharsDecimal
	   #:ImGuiInputTextFlags_CharsHexadecimal
	   #:ImGuiInputTextFlags_CharsUppercase
	   #:ImGuiInputTextFlags_CharsNoBlank
	   #:ImGuiInputTextFlags_AutoSelectAll
	   #:ImGuiInputTextFlags_EnterReturnsTrue
	   #:ImGuiInputTextFlags_CallbackCompletion
	   #:ImGuiInputTextFlags_CallbackHistory
	   #:ImGuiInputTextFlags_CallbackAlways
	   #:ImGuiInputTextFlags_CallbackCharFilter
	   #:ImGuiInputTextFlags_AllowTabInput
	   #:ImGuiInputTextFlags_CtrlEnterForNewLine
	   #:ImGuiInputTextFlags_NoHorizontalScroll
	   #:ImGuiInputTextFlags_AlwaysInsertMode
	   #:ImGuiInputTextFlags_ReadOnly
	   #:ImGuiInputTextFlags_Password
	   #:ImGuiInputTextFlags_NoUndoRedo

	   #:ImGuiTreeNodeFlags_Selected
	   #:ImGuiTreeNodeFlags_Framed
	   #:ImGuiTreeNodeFlags_AllowItemOverlap
	   #:ImGuiTreeNodeFlags_NoTreePushOnOpen
	   #:ImGuiTreeNodeFlags_NoAutoOpenOnLog
	   #:ImGuiTreeNodeFlags_DefaultOpen
	   #:ImGuiTreeNodeFlags_OpenOnDoubleClick
	   #:ImGuiTreeNodeFlags_OpenOnArrow
	   #:ImGuiTreeNodeFlags_Leaf
	   #:ImGuiTreeNodeFlags_Bullet
	   #:ImGuiTreeNodeFlags_FramePadding
	   #:ImGuiTreeNodeFlags_CollapsingHeader

	   #:ImGuiSelectableFlags_DontClosePopups
	   #:ImGuiSelectableFlags_SpanAllColumns
	   #:ImGuiSelectableFlags_AllowDoubleClick

	   #:ImGuiComboFlags_PopupAlignLeft
	   #:ImGuiComboFlags_HeightSmall
	   #:ImGuiComboFlags_HeightRegular
	   #:ImGuiComboFlags_HeightLarge
	   #:ImGuiComboFlags_HeightLargest
	   #:ImGuiComboFlags_HeightMask_

	   #:ImGuiFocusedFlags_ChildWindows
	   #:ImGuiFocusedFlags_RootWindow
	   #:ImGuiFocusedFlags_RootAndChildWindows

	   #:ImGuiHoveredFlags_ChildWindows
	   #:ImGuiHoveredFlags_RootWindow
	   #:ImGuiHoveredFlags_AllowWhenBlockedByPopup
	   #:ImGuiHoveredFlags_AllowWhenBlockedByActiveItem
	   #:ImGuiHoveredFlags_AllowWhenOverlapped
	   #:ImGuiHoveredFlags_RectOnly
	   #:ImGuiHoveredFlags_RootAndChildWindows

	   #:ImGuiDragDropFlags_SourceNoPreviewTooltip
	   #:ImGuiDragDropFlags_SourceNoDisableHover
	   #:ImGuiDragDropFlags_SourceNoHoldToOpenOthers
	   #:ImGuiDragDropFlags_SourceAllowNullID
	   #:ImGuiDragDropFlags_SourceExtern
	   #:ImGuiDragDropFlags_AcceptBeforeDelivery
	   #:ImGuiDragDropFlags_AcceptNoDrawDefaultRect
	   #:ImGuiDragDropFlags_AcceptPeekOnly

	   #:ImGuiKey_Tab
	   #:ImGuiKey_LeftArrow
	   #:ImGuiKey_RightArrow
	   #:ImGuiKey_UpArrow
	   #:ImGuiKey_DownArrow
	   #:ImGuiKey_PageUp
	   #:ImGuiKey_PageDown
	   #:ImGuiKey_Home
	   #:ImGuiKey_End
	   #:ImGuiKey_Delete
	   #:ImGuiKey_Backspace
	   #:ImGuiKey_Enter
	   #:ImGuiKey_Escape
	   #:ImGuiKey_A
	   #:ImGuiKey_C
	   #:ImGuiKey_V
	   #:ImGuiKey_X
	   #:ImGuiKey_Y
	   #:ImGuiKey_Z
	   #:ImGuiKey_COUNT

	   #:ImGuiCol_Text
	   #:ImGuiCol_TextDisabled
	   #:ImGuiCol_WindowBg
	   #:ImGuiCol_ChildBg
	   #:ImGuiCol_PopupBg
	   #:ImGuiCol_Border
	   #:ImGuiCol_BorderShadow
	   #:ImGuiCol_FrameBg
	   #:ImGuiCol_FrameBgHovered
	   #:ImGuiCol_FrameBgActive
	   #:ImGuiCol_TitleBg
	   #:ImGuiCol_TitleBgActive
	   #:ImGuiCol_TitleBgCollapsed
	   #:ImGuiCol_MenuBarBg
	   #:ImGuiCol_ScrollbarBg
	   #:ImGuiCol_ScrollbarGrab
	   #:ImGuiCol_ScrollbarGrabHovered
	   #:ImGuiCol_ScrollbarGrabActive
	   #:ImGuiCol_CheckMark
	   #:ImGuiCol_SliderGrab
	   #:ImGuiCol_SliderGrabActive
	   #:ImGuiCol_Button
	   #:ImGuiCol_ButtonHovered
	   #:ImGuiCol_ButtonActive
	   #:ImGuiCol_Header
	   #:ImGuiCol_HeaderHovered
	   #:ImGuiCol_HeaderActive
	   #:ImGuiCol_Separator
	   #:ImGuiCol_SeparatorHovered
	   #:ImGuiCol_SeparatorActive
	   #:ImGuiCol_ResizeGrip
	   #:ImGuiCol_ResizeGripHovered
	   #:ImGuiCol_ResizeGripActive
	   #:ImGuiCol_CloseButton
	   #:ImGuiCol_CloseButtonHovered
	   #:ImGuiCol_CloseButtonActive
	   #:ImGuiCol_PlotLines
	   #:ImGuiCol_PlotLinesHovered
	   #:ImGuiCol_PlotHistogram
	   #:ImGuiCol_PlotHistogramHovered
	   #:ImGuiCol_TextSelectedBg
	   #:ImGuiCol_ModalWindowDarkening
	   #:ImGuiCol_DragDropTarget
	   #:ImGuiCol_COUNT

	   #:ImGuiStyleVar_Alpha
	   #:ImGuiStyleVar_WindowPadding
	   #:ImGuiStyleVar_WindowRounding
	   #:ImGuiStyleVar_WindowBorderSize
	   #:ImGuiStyleVar_WindowMinSize
	   #:ImGuiStyleVar_ChildRounding
	   #:ImGuiStyleVar_ChildBorderSize
	   #:ImGuiStyleVar_PopupRounding
	   #:ImGuiStyleVar_PopupBorderSize
	   #:ImGuiStyleVar_FramePadding
	   #:ImGuiStyleVar_FrameRounding
	   #:ImGuiStyleVar_FrameBorderSize
	   #:ImGuiStyleVar_ItemSpacing
	   #:ImGuiStyleVar_ItemInnerSpacing
	   #:ImGuiStyleVar_IndentSpacing
	   #:ImGuiStyleVar_GrabMinSize
	   #:ImGuiStyleVar_ButtonTextAlign
	   #:ImGuiStyleVar_Count_

	   #:ImGuiColorEditFlags_NoAlpha
	   #:ImGuiColorEditFlags_NoPicker
	   #:ImGuiColorEditFlags_NoOptions
	   #:ImGuiColorEditFlags_NoSmallPreview
	   #:ImGuiColorEditFlags_NoInputs
	   #:ImGuiColorEditFlags_NoTooltip
	   #:ImGuiColorEditFlags_NoLabel
	   #:ImGuiColorEditFlags_NoSidePreview
	   #:ImGuiColorEditFlags_AlphaBar
	   #:ImGuiColorEditFlags_AlphaPreview
	   #:ImGuiColorEditFlags_AlphaPreviewHalf
	   #:ImGuiColorEditFlags_HDR
	   #:ImGuiColorEditFlags_RGB
	   #:ImGuiColorEditFlags_HSV
	   #:ImGuiColorEditFlags_HEX
	   #:ImGuiColorEditFlags_Uint8
	   #:ImGuiColorEditFlags_Float
	   #:ImGuiColorEditFlags_PickerHueBar
	   #:ImGuiColorEditFlags_PickerHueWheel

	   #:ImGuiMouseCursor_None
	   #:ImGuiMouseCursor_Arrow
	   #:ImGuiMouseCursor_TextInput
	   #:ImGuiMouseCursor_Move
	   #:ImGuiMouseCursor_ResizeNS
	   #:ImGuiMouseCursor_ResizeEW
	   #:ImGuiMouseCursor_ResizeNESW
	   #:ImGuiMouseCursor_ResizeNWSE
	   #:ImGuiMouseCursor_Count_

	   #:ImGuiCond_Always
	   #:ImGuiCond_Once
	   #:ImGuiCond_FirstUseEver
	   #:ImGuiCond_Appearing

	   #:ImDrawCornerFlags_TopLeft
	   #:ImDrawCornerFlags_TopRight
	   #:ImDrawCornerFlags_BotLeft
	   #:ImDrawCornerFlags_BotRight
	   #:ImDrawCornerFlags_Top
	   #:ImDrawCornerFlags_Bot
	   #:ImDrawCornerFlags_Left
	   #:ImDrawCornerFlags_Right
	   #:ImDrawCornerFlags_All

	   #:ImDrawListFlags_AntiAliasedLines
	   #:ImDrawListFlags_AntiAliasedFill

	   #:igGetIO
	   #:igGetStyle
	   #:igGetDrawData
	   #:igNewFrame
	   #:igRender
	   #:igEndFrame
	   #:igShutdown
	   #:igShowDemoWindow
	   #:igShowMetricsWindow
	   #:igShowStyleEditor
	   #:igShowStyleSelector
	   #:igShowFontSelector
	   #:igShowUserGuide
	   #:igBegin
	   #:igEnd
	   #:igBeginChild
	   #:igBeginChildEx
	   #:igEndChild
	   #:igGetContentRegionMax
	   #:igGetContentRegionAvail
	   #:igGetContentRegionAvailWidth
	   #:igGetWindowContentRegionMin
	   #:igGetWindowContentRegionMax
	   #:igGetWindowContentRegionWidth
	   #:igGetWindowDrawList
	   #:igGetWindowPos
	   #:igGetWindowSize
	   #:igGetWindowWidth
	   #:igGetWindowHeight
	   #:igIsWindowCollapsed
	   #:igIsWindowAppearing
	   #:igSetWindowFontScale
	   #:igSetNextWindowPos
	   #:igSetNextWindowSize
	   #:igSetNextWindowSizeConstraints
	   #:igSetNextWindowContentSize
	   #:igSetNextWindowCollapsed
	   #:igSetNextWindowFocus
	   #:igSetWindowPos
	   #:igSetWindowSize
	   #:igSetWindowCollapsed
	   #:igSetWindowFocus
	   #:igSetWindowPosByName
	   #:igSetWindowSize2
	   #:igSetWindowCollapsed2
	   #:igSetWindowFocus2
	   #:igGetScrollX
	   #:igGetScrollY
	   #:igGetScrollMaxX
	   #:igGetScrollMaxY
	   #:igSetScrollX
	   #:igSetScrollY
	   #:igSetScrollHere
	   #:igSetScrollFromPosY
	   #:igSetStateStorage
	   #:igGetStateStorage
	   #:igPushFont
	   #:igPopFont
	   #:igPushStyleColorU32
	   #:igPushStyleColor
	   #:igPopStyleColor
	   #:igPushStyleVar
	   #:igPushStyleVarVec
	   #:igPopStyleVar
	   #:igGetStyleColorVec4
	   #:igGetFont
	   #:igGetFontSize
	   #:igGetFontTexUvWhitePixel
	   #:igGetColorU32
	   #:igGetColorU32Vec
	   #:igGetColorU32U32
	   #:igPushItemWidth
	   #:igPopItemWidth
	   #:igCalcItemWidth
	   #:igPushTextWrapPos
	   #:igPopTextWrapPos
	   #:igPushAllowKeyboardFocus
	   #:igPopAllowKeyboardFocus
	   #:igPushButtonRepeat
	   #:igPopButtonRepeat
	   #:igSeparator
	   #:igSameLine
	   #:igNewLine
	   #:igSpacing
	   #:igDummy
	   #:igIndent
	   #:igUnindent
	   #:igBeginGroup
	   #:igEndGroup
	   #:igGetCursorPos
	   #:igGetCursorPosX
	   #:igGetCursorPosY
	   #:igSetCursorPos
	   #:igSetCursorPosX
	   #:igSetCursorPosY
	   #:igGetCursorStartPos
	   #:igGetCursorScreenPos
	   #:igSetCursorScreenPos
	   #:igAlignTextToFramePadding
	   #:igGetTextLineHeight
	   #:igGetTextLineHeightWithSpacing
	   #:igGetFrameHeight
	   #:igGetFrameHeightWithSpacing
	   #:igColumns
	   #:igNextColumn
	   #:igGetColumnIndex
	   #:igGetColumnWidth
	   #:igSetColumnWidth
	   #:igGetColumnOffset
	   #:igSetColumnOffset
	   #:igGetColumnsCount
	   #:igPushIDStr
	   #:igPushIDStrRange
	   #:igPushIDPtr
	   #:igPushIDInt
	   #:igPopID
	   #:igGetIDStr
	   #:igGetIDStrRange
	   #:igGetIDPtr
	   #:igTextUnformatted
	   #:igText
	   #:igTextV
	   #:igTextColored
	   #:igTextColoredV
	   #:igTextDisabled
	   #:igTextDisabledV
	   #:igTextWrapped
	   #:igTextWrappedV
	   #:igLabelText
	   #:igLabelTextV
	   #:igBulletText
	   #:igBulletTextV
	   #:igBullet
	   #:igButton
	   #:igSmallButton
	   #:igInvisibleButton
	   #:igImage
	   #:igImageButton
	   #:igCheckbox
	   #:igCheckboxFlags
	   #:igRadioButtonBool
	   #:igRadioButton
	   #:igPlotLines
	   #:igPlotLines2
	   #:igPlotHistogram
	   #:igPlotHistogram2
	   #:igProgressBar
	   #:igBeginCombo
	   #:igEndCombo
	   #:igCombo
	   #:igCombo2
	   #:igCombo3
	   #:igDragFloat
	   #:igDragFloat2
	   #:igDragFloat3
	   #:igDragFloat4
	   #:igDragFloatRange2
	   #:igDragInt
	   #:igDragInt2
	   #:igDragInt3
	   #:igDragInt4
	   #:igDragIntRange2
	   #:igInputText
	   #:igInputTextMultiline
	   #:igInputFloat
	   #:igInputFloat2
	   #:igInputFloat3
	   #:igInputFloat4
	   #:igInputInt
	   #:igInputInt2
	   #:igInputInt3
	   #:igInputInt4
	   #:igSliderFloat
	   #:igSliderFloat2
	   #:igSliderFloat3
	   #:igSliderFloat4
	   #:igSliderAngle
	   #:igSliderInt
	   #:igSliderInt2
	   #:igSliderInt3
	   #:igSliderInt4
	   #:igVSliderFloat
	   #:igVSliderInt
	   #:igColorEdit3
	   #:igColorEdit4
	   #:igColorPicker3
	   #:igColorPicker4
	   #:igColorButton
	   #:igSetColorEditOptions
	   #:igTreeNode
	   #:igTreeNodeStr
	   #:igTreeNodePtr
	   #:igTreeNodeStrV
	   #:igTreeNodePtrV
	   #:igTreeNodeEx
	   #:igTreeNodeExStr
	   #:igTreeNodeExPtr
	   #:igTreeNodeExV
	   #:igTreeNodeExPtr
	   #:igTreePushStr
	   #:igTreePushPtr
	   #:igTreePop
	   #:igTreeAdvanceToLabelPos
	   #:igGetTreeNodeToLabelSpacing
	   #:igSetNextTreeNodeOpen
	   #:igCollapsingHeader
	   #:igCollapsingHeaderEx
	   #:igSelectable
	   #:igSelectableEx
	   #:igListBox
	   #:igListBox2
	   #:igListBoxHeader
	   #:igListBoxHeader2
	   #:igListBoxFooter
	   #:igValueBool
	   #:igValueInt
	   #:igValueUInt
	   #:igValueFloat
	   #:igSetTooltip
	   #:igSetTooltipV
	   #:igBeginTooltip
	   #:igEndTooltip
	   #:igBeginMainMenuBar
	   #:igEndMainMenuBar
	   #:igBeginMenuBar
	   #:igEndMenuBar
	   #:igBeginMenu
	   #:igEndMenu
	   #:igMenuItem
	   #:igMenuItemPtr
	   #:igOpenPopup
	   #:igOpenPopupOnItemClick
	   #:igBeginPopup
	   #:igBeginPopupModal
	   #:igBeginPopupContextItem
	   #:igBeginPopupContextWindow
	   #:igBeginPopupContextVoid
	   #:igEndPopup
	   #:igIsPopupOpen
	   #:igCloseCurrentPopup
	   #:igLogToTTY
	   #:igLogToFile
	   #:igLogToClipboard
	   #:igLogFinish
	   #:igLogButtons
	   #:igLogText
	   #:igBeginDragDropSource
	   #:igSetDragDropPayload
	   #:igEndDragDropSource
	   #:igBeginDragDropTarget
	   #:igAcceptDragDropPayload
	   #:igEndDragDropPayload
	   #:igPushClipRect
	   #:igPopClipRect
	   #:igStyleColorsClassic
	   #:igStyleColorsDark
	   #:igStyleColorsLight
	   #:igSetItemDefaultFocus
	   #:igSetKeyboardFocusHere
	   #:igIsItemHovered
	   #:igIsItemActive
	   #:igIsItemClicked
	   #:igIsItemVisible
	   #:igIsAnyItemHovered
	   #:igIsAnyItemActive
	   #:igGetItemRectMin
	   #:igGetItemRectMax
	   #:igGetItemRectSize
	   #:igSetItemAllowOverlap
	   #:igIsWindowFocused
	   #:igIsWindowHovered
	   #:igIsAnyWindowFocused
	   #:igIsAnyWindowHovered
	   #:igIsRectVisible
	   #:igIsRectVisible2
	   #:igGetTime
	   #:igGetFrameCount
	   #:igGetOverlayDrawList
	   #:igGetDrawListSharedData
	   #:igGetStyleColorName
	   #:igCalcItemRectClosestPoint
	   #:igCalcTextSize
	   #:igCalcListClipping
	   #:igBeginChildFrame
	   #:igEndChildFrame
	   #:igColorConvertU32ToFloat4
	   #:igColorConvertFloat4ToU32
	   #:igColorConvertRGBtoHSV
	   #:igColorConvertHSVtoRGB
	   #:igGetKeyIndex
	   #:igIsKeyDown
	   #:igIsKeyPressed
	   #:igIsKeyReleased
	   #:igGetKeyPressedAmount
	   #:igIsMouseDown
	   #:igIsMouseClicked
	   #:igIsMouseDoubleClicked
	   #:igIsMouseReleased
	   #:igIsMouseDragging
	   #:igIsMouseHoveringRect
	   #:igIsMousePosValid
	   #:igGetMousePos
	   #:igGetMousePosOnOpeningCurrentPopup
	   #:igGetMouseDragDelta
	   #:igResetMouseDragDelta
	   #:igGetMouseCursor
	   #:igSetMouseCursor
	   #:igCaptureKeyboardFromApp
	   #:igMemAlloc
	   #:igMemFree
	   #:igGetClipboardText
	   #:igSetClipboardText
	   #:igGetVersion
	   #:igCreateContext
	   #:igDestroyContext
	   #:igGetCurrentContext
	   #:igSetCurrentContext
	   #:ImFontConfig_DefaultConstructor
	   #:ImGuiIO_AddInputCharacter
	   #:ImGuiIO_AddInputCharactersUTF8
	   #:ImGuiIO_ClearInputCharacters
	   #:ImGuiTextFilter_Create
	   #:ImGuiTextFilter_Destroy
	   #:ImGuiTextFilter_Clear
	   #:ImGuiTextFilter_Draw
	   #:ImGuiTextFilter_PassFilter
	   #:ImGuiTextFilter_IsActive
	   #:ImGuiTextFilter_Build
	   #:ImGuiTextFilter_GetInputBuf
	   #:ImGuiTextBuffer_Create
	   #:ImGuiTextBuffer_Destroy
	   #:ImGuiTextBuffer_index
	   #:ImGuiTextBuffer_begin
	   #:ImGuiTextBuffer_end
	   #:ImGuiTextBuffer_size
	   #:ImGuiTextBuffer_empty
	   #:ImGuiTextBuffer_clear
	   #:ImGuiTextBuffer_c_str
	   #:ImGuiTextBuffer_appendf
	   #:ImGuiTextBuffer_appendfv
	   #:ImGuiStorage_Create
	   #:ImGuiStorage_Destroy
	   #:ImGuiStorage_GetInt
	   #:ImGuiStorage_SetInt
	   #:ImGuiStorage_GetBool
	   #:ImGuiStorage_SetBool
	   #:ImGuiStorage_GetFloat
	   #:ImGuiStorage_SetFloat
	   #:ImGuiStorage_GetVoidPtr
	   #:ImGuiStorage_SetVoidPtr
	   #:ImGuiStorage_GetIntRef
	   #:ImGuiStorage_GetBoolRef
	   #:ImGuiStorage_GetFloatRef
	   #:ImGuiStorage_GetVoidPtrRef
	   #:ImGuiStorage_SetAllInt
	   #:ImGuiTextEditCallbackData_DeleteChars
	   #:ImGuiTextEditCallbackData_InsertChars
	   #:ImGuiTextEditCallbackData_HasSelection
	   #:ImGuiListClipper_Step
	   #:ImGuiListClipper_Begin
	   #:ImGuiListClipper_End
	   #:ImGuiListClipper_GetDisplayStart
	   #:ImGuiListClipper_GetDisplayEnd
	   #:ImDrawList_GetVertexBufferSize
	   #:ImDrawList_GetVertexPtr
	   #:ImDrawList_GetIndexBufferSize
	   #:ImDrawList_GetIndexPtr
	   #:ImDrawList_GetCmdSize
	   #:ImDrawList_GetCmdPtr
	   #:ImDrawList_Clear
	   #:ImDrawList_ClearFreeMemory
	   #:ImDrawList_PushClipRect
	   #:ImDrawList_PushClipRectFullScreen
	   #:ImDrawList_PopClipRect
	   #:ImDrawList_PushTextureID
	   #:ImDrawList_PopTextureID
	   #:ImDrawList_GetClipRectMin
	   #:ImDrawList_GetClipRectMax
	   #:ImDrawList_AddLine
	   #:ImDrawList_AddRect
	   #:ImDrawList_AddRectFilled
	   #:ImDrawList_AddRectFilledMultiColor
	   #:ImDrawList_AddQuad
	   #:ImDrawList_AddQuadFilled
	   #:ImDrawList_AddTriangle
	   #:ImDrawList_AddTriangleFilled
	   #:ImDrawList_AddCircle
	   #:ImDrawList_AddCircleFilled
	   #:ImDrawList_AddText
	   #:ImDrawList_AddTextExt
	   #:ImDrawList_AddImage
	   #:ImDrawList_AddImageQuad
	   #:ImDrawList_AddImageRounded
	   #:ImDrawList_AddPolyline
	   #:ImDrawList_AddConvexPolyFilled
	   #:ImDrawList_AddBezierCurve
	   #:ImDrawList_PathClear
	   #:ImDrawList_PathLineTo
	   #:ImDrawList_PathLineToMergeDuplicate
	   #:ImDrawList_PathFillConvex
	   #:ImDrawList_PathStroke
	   #:ImDrawList_PathArcTo
	   #:ImDrawList_PathArcToFast
	   #:ImDrawList_PathBezierCurveTo
	   #:ImDrawList_PathRect
	   #:ImDrawList_ChannelsSplit
	   #:ImDrawList_ChannelsMerge
	   #:ImDrawList_ChannelsSetCurrent
	   #:ImDrawList_AddCallback
	   #:ImDrawList_AddDrawCmd
	   #:ImDrawList_PrimReserve
	   #:ImDrawList_PrimRect
	   #:ImDrawList_PrimRectUV
	   #:ImDrawList_PrimQuadUV
	   #:ImDrawList_PrimWriteVtx
	   #:ImDrawList_PrimWriteIdx
	   #:ImDrawList_PrimVtx
	   #:ImDrawList_UpdateClipRect
	   #:ImDrawList_UpdateTextureID
	   #:ImDrawData_DeIndexAllBuffers
	   #:ImDrawData_ScaleClipRects
	   #:ImFontAtlas_GetTexDataAsRGBA32
	   #:ImFontAtlas_GetTexDataAsAlpha8
	   #:ImFontAtlas_SetTexID
	   #:ImFontAtlas_AddFont
	   #:ImFontAtlas_AddFontDefault
	   #:ImFontAtlas_AddFontFromFileTTF
	   #:ImFontAtlas_AddFontFromMemoryTTF
	   #:ImFontAtlas_AddFontFromMemoryCompressedTTF
	   #:ImFontAtlas_AddFontFromMemoryCompressedBase85TTF
	   #:ImFontAtlas_ClearTexData
	   #:ImFontAtlas_Clear
	   #:ImFontAtlas_GetGlyphRangesDefault
	   #:ImFontAtlas_GetGlyphRangesKorean
	   #:ImFontAtlas_GetGlyphRangesJapanese
	   #:ImFontAtlas_GetGlyphRangesChinese
	   #:ImFontAtlas_GetGlyphRangesCyrillic
	   #:ImFontAtlas_GetGlyphRangesThai
	   #:ImFontAtlas_GetTexID
	   #:ImFontAtlas_GetTexPixelsAlpha8
	   #:ImFontAtlas_GetTexPixelsRGBA32
	   #:ImFontAtlas_GetTexWidth
	   #:ImFontAtlas_GetTexHeight
	   #:ImFontAtlas_GetTexDesiredWidth
	   #:ImFontAtlas_SetTexDesiredWidth
	   #:ImFontAtlas_GetTexGlyphPadding
	   #:ImFontAtlas_SetTexGlyphPadding
	   #:ImFontAtlas_GetTexUvWhitePixel
	   #:ImFontAtlas_Fonts_size
	   #:ImFontAtlas_Fonts_index
	   #:ImFont_GetFontSize
	   #:ImFont_SetFontSize
	   #:ImFont_GetScale
	   #:ImFont_SetScale
	   #:ImFont_GetDisplayOffset
	   #:ImFont_GetFallbackGlyph
	   #:ImFont_SetFallbackGlyph
	   #:ImFont_GetFallbackAdvanceX
	   #:ImFont_GetFallbackChar
	   #:ImFont_GetConfigDataCount
	   #:ImFont_GetConfigData
	   #:ImFont_GetContainerAtlas
	   #:ImFont_GetAscent
	   #:ImFont_GetDescent
	   #:ImFont_GetMetricsTotalSurface
	   #:ImFont_ClearOutputData
	   #:ImFont_BuildLookupTable
	   #:ImFont_FindGlyph
	   #:ImFont_SetFallbackChar
	   #:ImFont_GetCharAdvance
	   #:ImFont_IsLoaded
	   #:ImFont_GetDebugName
	   #:ImFont_CalcTextSizeA
	   #:ImFont_CalcWordWrapPositionA
	   #:ImFont_RenderChar
	   #:ImFont_RenderText
	   #:ImFont_Glyphs_size
	   #:ImFont_Glyphs_index
	   #:ImFont_IndexXAdvance_size
	   #:ImFont_IndexXAdvance_index
	   #:ImFont_IndexLookup_size
	   #:ImFont_IndexLookup_index))
