(in-package :cl-user)

(defpackage :vulkan-toolkit
  (:nicknames :vktk)
  (:use :cl :cffi :imgui :glfw :vulkan :3d-vectors :3d-matrices :lisp-unit)
  (:import-from :sb-ext #:quit #:exit)

  (:export #:*debug*
	   #:with-vk-struct
	   #:h
	   #:device
	   #:allocation-callbacks
	   #:+null-allocator+
	   #:pipeline-cache
	   #:+null-pipeline-cache+
	   #:instance
	   #:create-instance
	   #:destroy-instance
	   #:physical-devices
	   #:command-pools
	   #:sgpu-device
	   #:+max-concurrently-processed-frames+
	   #:*assets-dir*
	   #:enumerate-instance-layer-properties
	   #:enumerate-instance-extension-properties
	   #:available-layers
	   #:available-extensions
	   #:swapchain
	   #:surface-format
	   #:number-of-images
	   #:color-image-views
	   #:depth-image-view
	   #:depth-image
	   #:framebuffers
	   #:application
	   #:main-window
	   #:render-surface
	   #:render-pass
	   #:find-window
	   #:create-window
	   #:destroy-window
	   #:window-should-close-p
	   #:window-title
	   #:get-window-pos
	   #:set-window-pos
	   #:get-cursor-pos
	   #:get-window-size
	   #:focus-window
	   #:hide-window
	   #:show-window
	   #:maximize-window
	   #:restore-window
	   #:window-frame-size
	   #:get-framebuffer-size
	   #:set-window-size
	   #:set-window-aspect-ratio
	   #:set-window-size-limits
	   #:callback-name
	   #:allocator
	   #:surface-format-format
	   #:surface-format-color-space
	   #:paired-gpu
	   #:window
	   #:queue-family-index
	   #:capabilities
	   #:supported-formats
	   #:presentation-modes
	   #:get-surface-formats
	   #:find-supported-depth-format
	   #:find-suppported-format
	   #:get-present-modes
	   #:get-queue-family-index-with-wsi-support
	   #:create-window-surface
	   #:initialize-window-surface
	   #:has-robust-buffer-access-p
	   #:has-full-draw-index-uint32-p
	   #:has-image-cube-array-p
	   #:has-independent-blend-p
	   #:has-geometry-shader-p
	   #:has-tessellation-shader-p
	   #:has-sample-rate-shading-p
	   #:has-dual-src-blend-p
	   #:has-logic-op-p
	   #:has-multi-draw-indirect-p
	   #:has-draw-indirect-first-instance-p
	   #:has-depth-clamp-p
	   #:has-depth-bias-clamp-p
	   #:has-fill-mode-non-solid-p
	   #:has-depth-bounds-p
	   #:has-wide-lines-p
	   #:has-large-points-p
	   #:has-alpha-to-one-p
	   #:has-multi-viewport-p
	   #:has-sampler-anisotropy-p
	   #:has-texture-compression-etc2-p
	   #:has-texture-compression-astc-ldr-p
	   #:has-texture-compression-bc-p
	   #:has-occlusion-query-precise-p
	   #:has-pipeline-statistics-query-p
	   #:has-vertex-pipeline-stores-and-atomics-p
	   #:has-fragment-stores-and-atomics-p
	   #:has-shader-tessellation-and-geometry-point-size-p
	   #:has-shader-image-gather-extended-p
	   #:has-shader-storage-image-extended-formats-p
	   #:has-shader-storage-image-multisample-p
	   #:has-shader-storage-image-read-without-format-p
	   #:has-shader-storage-image-write-without-format-p
	   #:has-shader-uniform-buffer-array-dynamic-indexing-p
	   #:has-shader-sampled-image-array-dynamic-indexing-p
	   #:has-shader-storage-buffer-array-dynamic-indexing-p
	   #:has-shader-storage-image-array-dynamic-indexing-p
	   #:has-shader-clip-distance-p
	   #:has-shader-cull-distance-p
	   #:has-shader-float64-p
	   #:has-shader-int64-p
	   #:has-shader-int16-p
	   #:has-shader-resource-residency-p
	   #:has-shader-resource-min-lod-p
	   #:has-sparse-binding-p
	   #:has-sparse-residency-buffer-p
	   #:has-sparse-residency-image-2D-p
	   #:has-sparse-residency-image-3D-p
	   #:has-sparse-residency2-samples-p
	   #:has-sparse-residency4-samples-p
	   #:has-sparse-residency8-samples-p
	   #:has-sparse-residency16-samples-p
	   #:has-sparse-residency-aliased-p
	   #:has-variable-multisample-rate-p
	   #:has-inherited-queries-p
	   #:max-image-dimension-1D
	   #:max-image-dimension-2D
	   #:max-image-dimension-3D
	   #:max-image-dimension-cube
	   #:max-image-array-layers
	   #:max-texel-buffer-elements
	   #:max-uniform-buffer-range
	   #:max-storage-buffer-range
	   #:max-push-constants-size
	   #:max-memory-allocation-count
	   #:max-sampler-allocation-count
	   #:buffer-image-granularity
	   #:sparse-address-space-size
	   #:max-bound-descriptor-sets
	   #:max-per-stage-descriptor-samplers
	   #:max-per-stage-descriptor-uniform-buffers
	   #:max-per-stage-descriptor-storage-buffers
	   #:max-per-stage-descriptor-sampled-images
	   #:max-per-stage-descriptor-storage-images
	   #:max-per-stage-descriptor-input-attachments
	   #:max-per-stage-resources
	   #:max-descriptor-set-samplers
	   #:max-descriptor-set-uniform-buffers
	   #:max-descriptor-set-uniform-buffers-dynamic
	   #:max-descriptor-set-storage-buffers
	   #:max-descriptor-set-storage-buffers-dynamic
	   #:max-descriptor-set-sampled-images
	   #:max-descriptor-set-storage-images
	   #:max-descriptor-set-input-attachments
	   #:max-vertex-input-attributes
	   #:max-vertex-input-bindings
	   #:max-vertex-input-attribute-offset
	   #:max-vertex-input-binding-stride
	   #:max-vertex-output-components
	   #:max-tessellation-generation-level
	   #:max-tessellation-patch-size
	   #:max-tessellation-control-per-vertex-input-components
	   #:max-tessellation-control-per-vertex-output-components
	   #:max-tessellation-control-per-patch-output-components
	   #:max-tessellation-control-total-output-components
	   #:max-tessellation-evaluation-input-components
	   #:max-tessellation-evaluation-output-components
	   #:max-geometry-shader-invocations
	   #:max-geometry-input-components
	   #:max-geometry-output-components
	   #:max-geometry-output-vertices
	   #:max-geometry-total-output-components
	   #:max-fragment-input-components
	   #:max-fragment-output-attachments
	   #:max-fragment-dual-src-attachments
	   #:max-fragment-combined-output-resources
	   #:max-compute-shared-memory-size
	   #:max-compute-work-group-count
	   #:max-compute-work-group-invocations
	   #:max-compute-work-group-size
	   #:sub-pixel-precision-bits
	   #:sub-texel-precision-bits
	   #:mipmap-precision-bits
	   #:max-draw-indexed-index-value
	   #:max-draw-indirect-count
	   #:max-sampler-lod-bias
	   #:max-sampler-anisotropy
	   #:max-viewports
	   #:max-viewport-dimensions
	   #:viewport-bounds-range
	   #:viewport-sub-pixel-bits
	   #:min-memory-map-alignment
	   #:min-texel-buffer-offset-alignment
	   #:min-uniform-buffer-offset-alignment
	   #:min-storage-buffer-offset-alignment
	   #:min-texel-offset
	   #:max-texel-offset
	   #:min-texel-gather-offset
	   #:max-texel-gather-offset
	   #:min-interpolation-offset
	   #:max-interpolation-offset
	   #:sub-pixel-interpolation-offset-bits
	   #:max-framebuffer-width
	   #:max-framebuffer-height
	   #:max-framebuffer-layers
	   #:framebuffer-color-sample-counts
	   #:framebuffer-depth-sample-counts
	   #:framebuffer-stencil-sample-counts
	   #:framebuffer-no-attachments-sample-counts
	   #:max-color-attachments
	   #:sampled-image-color-sample-counts
	   #:sampled-image-integer-sample-counts
	   #:sampled-image-depth-sample-counts
	   #:sampled-image-stencil-sample-counts
	   #:storage-image-sample-counts
	   #:max-sample-mask-words
	   #:timestamp-compute-and-graphics
	   #:timestamp-period
	   #:max-clip-distances
	   #:max-cull-distances
	   #:max-combined-clip-and-cull-distances
	   #:discrete-queue-priorities
	   #:point-size-range
	   #:line-width-range
	   #:point-size-granularity
	   #:line-width-granularity
	   #:strict-lines
	   #:standard-sample-locations
	   #:optimal-buffer-copy-offset-alignment
	   #:optimal-buffer-copy-row-pitch-alignment
	   #:non-coherent-atom-size
	   #:physical-device
	   #:device-name
	   #:device-type
	   #:device-id
	   #:vendor-id
	   #:driver-version
	   #:api-version
	   #:memory-properties
	   #:queue-families
	   #:queue-family
	   #:queue-flags
	   #:queue-count
	   #:graphics-queue-family-p
	   #:compute-queue-family-p
	   #:transfer-queue-family-p
	   #:sparse-binding-queue-family-p
	   #:extent-3D
	   #:extent-3D-width
	   #:extent-3D-height
	   #:extent-3D-depth
	   #:min-image-transfer-granularity-width
	   #:min-image-transfer-granularity-height
	   #:min-image-transfer-granularity-depth
	   #:memory-type
	   #:memory-type-device-local-p
	   #:memory-type-host-visible-p
	   #:memory-type-host-coherent-p
	   #:memory-type-host-cached-p
	   #:memory-type-lazy-allocated-p
	   #:memory-type-protected-p
	   #:memory-heap
	   #:memory-heap-device-local-p
	   #:get-physical-device-memory-properties
	   #:get-physical-device-queue-family-properties
	   #:surface-capabilities
	   #:min-image-count
	   #:max-image-count
	   #:current-extent
	   #:min-image-extent
	   #:max-image-extent
	   #:max-image-array-layers
	   #:supported-transform
	   #:supported-composite-alpha
	   #:supported-usage-flags
	   #:extent-2D
	   #:capabilities-current-extent-width
	   #:capabilities-current-extent-height
	   #:get-physical-device-surface-capabilities-khr
	   #:enumerate-physical-devices
	   #:queue
	   #:dedicated-queue
	   #:multipurpose-queue
	   #:get-device-queue
	   #:queue-family
	   #:graphics-queue-family-p
	   #:compute-queue-family-p
	   #:transfer-queue-family-p
	   #:sparse-binding-queue-family-p
	   #:create-logical-device
	   #:create-swapchain
	   #:get-swapchain-images-khr
	   #:create-image-view
	   #:create-depth-image-view
	   #:create-image-views
	   #:initialize-swapchain
	   #:render-pass
	   #:color-attachment
	   #:depth-attachment
	   #:attachment-name
	   #:attachment-format
	   #:samples
	   #:load-op
	   #:store-op
	   #:stencil-load-op
	   #:stencil-store-op
	   #:initial-layout
	   #:final-layout
	   #:reference-layout
	   #:subpass
	   #:create-render-pass
	   #:descriptor-set-layout-binding
	   #:uniform-buffer-for-vertex-shader-dsl-binding
	   #:uniform-buffer-for-geomety-shader-dsl-binding
	   #:descriptor-set-layout
	   #:create-descriptor-set-layout
	   #:fill-pipeline-shader-stage-create-info
	   #:fill-vertex-input-binding-description
	   #:fill-vertex-input-attribute-description
	   #:fill-pipeline-vertex-input-state-create-info
	   #:fill-pipeline-input-assembly-state-create-info
	   #:fill-viewport-structure
	   #:fill-scissor-structure
	   #:fill-pipeline-viewport-state-create-info
	   #:fill-pipeline-rasterization-state-create-info
	   #:fill-pipeline-multisample-state-create-info
	   #:fill-graphics-pipeline-create-info
	   #:fill-pipeline-depth-stencil-state-create-info
	   #:fill-pipeline-dynamic-state-create-info
	   #:fill-pipeline-color-blend-state-create-info
	   #:fill-pipeline-color-blend-attachment-state
	   #:push-constant-range
	   #:pipeline-layout
	   #:push-constant-range-stage-flags
	   #:push-constant-range-offset
	   #:push-constant-range-size
	   #:descriptor-set-layouts
	   #:push-constant-ranges
	   #:create-pipeline-layout
	   #:create-shader-module-from-file
	   #:create-shader-module
	   #:vec2
	   #:vec3
	   #:pipeline
	   #:vertex-shader
	   #:geometry-shader
	   #:fragment-shader
	   #:vertex-input-attribute-description
	   #:location
	   #:binding
	   #:desc-format
	   #:offset
	   #:create-graphics-pipeline
	   #:command-pool
	   #:create-command-pool
	   #:find-command-pool
	   #:recreate-swapchain
	   #:destroy-command-pool
	   #:destroy-framebuffers
	   #:destroy-shader-module
	   #:destroy-image-view
	   #:destroy-image
	   #:destroy-framebuffer
	   #:free-command-buffer
	   #:destroy-swapchain
	   #:destroy-pipeline
	   #:destroy-pipeline-layout
	   #:destroy-descriptor-sets
	   #:set-window-close-callback
	   #:set-framebuffer-size-callback
	   #:setup-framebuffers
	   #:vertex-buffer
	   #:index-buffer
	   #:create-buffer-1
	   #:find-memory-type
	   #:allocate-buffer-memory
	   #:bind-buffer-memory
	   #:copy-buffer
	   #:memcpy
	   #:create-buffer
	   #:find-queue
	   #:create-vertex-buffer
	   #:create-index-buffer
	   #:uniform-buffer
	   #:create-uniform-buffer
	   #:create-image
	   #:create-depth-image
	   #:create-descriptor-pool
	   #:create-descriptor-pool-1
	   #:descriptor-set
	   #:allocate-descriptor-set
	   #:create-descriptor-set
	   #:command-buffer
	   #:fence
	   #:semaphore
	   #:create-command-buffer
	   #:begin-single-time-commands
	   #:end-single-time-commands
	   #:has-stencil-component-p
	   #:transition-image-layout
	   #:mat4
	   #:pick-graphics-gpu
	   ))
